### ISSUE TITLE
install Sass in vagrantfile

### ISSUE THREAD

**Issue by danrschlosser** [adicu/adi-website#135]
<a href="https://github.com/natebrennand"><img src="https://avatars.githubusercontent.com/u/2801090?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [natebrennand](https://github.com/natebrennand)**
_Monday Jan 19, 2015 at 21:40 GMT_
_Originally opened as https://github.com/danrschlosser/eventum/issues/135_

----

prevent #134 from repeating

**Comment by danrschlosser** [comment]
The install command is being run, am I missing something?

https://github.com/adicu/adi-website/blob/master/config/bootstrap.sh#L21

**Comment by danrschlosser** [comment]
ping @natebrennand

**Comment by natebrennand** [comment]
What's the error being thrown?

**Comment by danrschlosser** [comment]
I think this has been fixed, seeing as we are installing sass in vagrant.
