### ISSUE TITLE
image upload needs better error messages

### ISSUE THREAD

**Issue by danrschlosser** [adicu/adi-website#140]
<a href="https://github.com/natebrennand"><img src="https://avatars.githubusercontent.com/u/2801090?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [natebrennand](https://github.com/natebrennand)**
_Sunday Feb 15, 2015 at 22:56 GMT_
_Originally opened as https://github.com/danrschlosser/eventum/issues/140_

----

If you hit "Upload" without choosing a file then the Python error is flashed for a dictionary key miss.
I think this UI could be a lot clearer if there was a more detailed error message given, or if hitting "Upload" defaults to the "Choose file" option whenever there is not a value chosen for a file

**Comment by adamreis** [comment]
https://www.dropbox.com/s/e9n9gy2evio2ey5/Screenshot%202015-03-29%2013.15.49.png?dl=0)

**Comment by adamreis** [comment]
https://www.dropbox.com/s/e9n9gy2evio2ey5/Screenshot%202015-03-29%2013.15.49.png?dl=0)

**Comment by danrschlosser** [comment]
@benlowkh
