### ISSUE TITLE
create user UI needs more detail

### ISSUE THREAD

**Issue by natebrennand** [adicu/adi-website#151]
So this menu is very simple which is nice, but it's not obvious what the differences between editor/publisher/admin are.

Idk if we need to include `Fake User` when the app is running w/o debug mode on either.

![screenshot 2015-03-27 17 34 14](https://cloud.githubusercontent.com/assets/2801090/6877444/889acafa-d4a7-11e4-8b0d-2d8f653e1a77.png)

**Comment by danrschlosser** [comment]
Let's rename "Fake User" to "Guest Writer", and give a table of permissions for each person
