### ISSUE TITLE
Edit Event Page buttons are a bit wacky

### ISSUE THREAD

**Issue by eunicekokor** [adicu/adi-website#168]
![screenshot 2015-04-07 13 56 11](https://cloud.githubusercontent.com/assets/5273390/7029853/5c2e8404-dd2e-11e4-9a4f-63cc660998e6.png)

responsive view:
![screenshot 2015-04-07 14 02 25](https://cloud.githubusercontent.com/assets/5273390/7029913/dd9b463a-dd2e-11e4-85ff-173fc79dfbff.png)

**Comment by danrschlosser** [comment]
Try a hard refresh, cmd+shift+R

I think it is just cached CSS

**Comment by eunicekokor** [comment]
Nope! It's only the create a new event page that looks correct

**Comment by danrschlosser** [comment]
Oh wow, you're right!

**Comment by eunicekokor** [comment]
Looking at it now. How do I get admin access while testing on localhost?

**Comment by eunicekokor** [comment]
@bluemelodia looks like the scss edits in #160 that fix nav position stuff may affect this.
