### ISSUE TITLE
Use Consul Loader

### ISSUE THREAD

**Issue by schlosser** [adicu/adi-website#182]
We should use https://github.com/natebrennand/consul_loader for loading consul variables from JSON

We should add this to vagrant:

``` bash
apt-get install golang 
export GOPATH=/go 
go get github.com/natebrennand/consul_loader 
export PATH=$PATH:/go/bin
consul_loader <config>... # run the script
```

**Comment by natebrennand** [comment]
exact command should look like this I think:

```
./consul_loader -srcJSON=config/dev.json -destKey=/density
```

**Comment by danrschlosser** [comment]
And we'll create files: `config/dev.settings.json` and `config/prod.settings.json`
