### ISSUE TITLE
Docker deletes uploaded images

### ISSUE THREAD

**Issue by danrschlosser** [adicu/adi-website#194]
:red_circle: **Until this is resolved, we can not deploy** :red_circle: 

@natebrennand @thebrianzeng 

I found out that when we upload images to Eventum and docker is running, the images are saved in docker, but not anywhere under `/srv/adi-website/www`:

```bash
root@adi-website:/# find -name "functional-cover.png"
./var/lib/docker/aufs/diff/aff6cc62ed2bafcc00d861c1fce27098ee79e3e6c573c9537d457da17747052b/app/static/img/uploaded/functional-cover.png
./var/lib/docker/aufs/mnt/aff6cc62ed2bafcc00d861c1fce27098ee79e3e6c573c9537d457da17747052b/app/static/img/uploaded/functional-cover.png
```

The result of this is that **every time we deploy, all images that we uploaded since the last deployment are lost**.  We need to either:
1. Configure Docker to sync folders to `/srv/adi-website/www` somehow
2. Configure Eventum to save images to somewhere else on the machine, and serve them statically. (We could save them on some sort of `static.adicu.com`.)
3. Some other option that I don't know involving Docker configurations

**Comment by danrschlosser** [comment]
Looks like one solution may be changing:

```
docker run --net=host -v $ADI_WWW/../logs:/opt/logs -d --name="adi-website" adi-website
```

to 

```
docker run --net=host -v $ADI_WWW/../logs:/opt/logs -v $ADI_WWW/app/static/img/uploaded:/app/static/img/uploaded -d --name="adi-website" adi-website
``` 

http://docs.docker.com/userguide/dockervolumes/#mount-a-host-directory-as-a-data-volume

**Comment by natebrennand** [comment]
all of these docker commands should be moved to a Makefile for sanity.

**Comment by danrschlosser** [comment]
Does that command look right?

**Comment by thebrianzeng** [comment]
yeah, i think that's right

**Comment by natebrennand** [comment]
Looks correct to me, though I think we should separate the lines for readability.
```
docker run \
    --net=host \
    -v $ADI_WWW/../logs:/opt/logs \
    -v $ADI_WWW/app/static/img/uploaded:/app/static/img/uploaded \
    --name="adi-website" adi-website \
    -d
````

**Comment by danrschlosser** [comment]
Fixed! That's live
