### ISSUE TITLE
makefile for docker commands

### ISSUE THREAD

**Issue by natebrennand** [adicu/adi-website#196]
- build
- restart

idk what else we would need

**Comment by danrschlosser** [comment]
Ideally we could have some sort of no-downtime command that brings one up then switches traffic then brings the other down? unclear

**Comment by danrschlosser** [comment]
some sort of nginx hotswap maybe?

**Comment by natebrennand** [comment]
So I don't think that you can dynamically change the port of an existing container.
So the solution would be change nginx I guess?

**Comment by natebrennand** [comment]
So I think the "real" solution is to use something like HAProxy so that you have a single address that's programmatically routed to another address(s). Generally this means using a load balancer. We might be able to try this with something like HAProxy.

see blog post: http://docs.quay.io/solution/zero-downtime-deployments.html

However, nginx has this feature on the way!
https://news.ycombinator.com/item?id=9408626

**Comment by natebrennand** [comment]
Alternatively, this could probably be a bash script probably. We could move the nginx configurations into separate files and just use `sed` to change the local port.

1. get port of current container
- start new container
- change nginx config w/ current port
- restart nginx
- kill old container

Nginx does not have a programmatic API unfortunately. This is what makes something like HAProxy attractive. But adding even more new tech is not desirable.

---------------

This process could also be hooked up to the [deployments api](https://developer.github.com/v3/repos/deployments/) and manage deployments automatically. That way we could add [locks](https://www.consul.io/docs/commands/lock.html) for each project so that deployments don't overlap.
