### ISSUE TITLE
<H2> styling in blog posts is weak

### ISSUE THREAD

**Issue by schlosser** [adicu/adi-website#212]
Could we get some margins up in there?  space is everything!

![screen shot 2015-05-02 at 3 00 36 am](https://cloud.githubusercontent.com/assets/2433509/7440251/7faa7eb8-f077-11e4-9db2-00201d14a53a.png)

**Comment by danrschlosser** [comment]
Looks like `margin: 1.5rem 0 0.5rem;` on `h2`s in blog posts should do it!
