### ISSUE TITLE
Add Udemy Python Course to Resources

### ISSUE THREAD

**Issue by danrschlosser** [adicu/adi-website#224]
We should add [Udemy's Beginner's Guide to Python](https://blog.udemy.com/python-tutorial/) to the resources page

**Comment by danrschlosser** [comment]
Two more: 
- Bootstrap: https://blog.udemy.com/bootstrap-tutorial-a-guide-for-beginners/

**Comment by eunicekokor** [comment]
Another One
- Ruby on Rails: https://blog.udemy.com/ruby-on-rails-tutorial-learn-from-scratch/

**Comment by natebrennand** [comment]
Jw, has anyone vetted one of these courses?

**Comment by eunicekokor** [comment]
I scrolled through the Python one and read bits and pieces of Bootstrap.
On Wed, Aug 19, 2015 at 11:37 PM Nate <notifications@github.com> wrote:

> Jw, has anyone vetted one of these courses?
>
> On Wed, Aug 19, 2015, 8:30 PM eunice <notifications@github.com> wrote:
>
> > Another One
> >
> > - Ruby on Rails:
> > https://blog.udemy.com/ruby-on-rails-tutorial-learn-from-scratch/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/adicu/adi-website/issues/224#issuecomment-132874526
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adicu/adi-website/issues/224#issuecomment-132906897>.
>
-- 
Eunice Kokor
