### ISSUE TITLE
s/Wev/Web

### ISSUE THREAD

**Issue by natebrennand** [adicu/adi-website#233]
On https://adicu.com/resources:

<img width="1042" alt="screenshot 2015-09-04 16 36 10" src="https://cloud.githubusercontent.com/assets/2801090/9696344/20ae6b40-5323-11e5-8d27-b899db3aced1.png">

**Comment by eunicekokor** [comment]
just the Wev --> Web? is there anything else? Just making sure what s/Wev/Web means

**Comment by natebrennand** [comment]
Ya, that is correct.
Sorry, that was not as detailed as I should have made it. `sed` is a tool for replacing instances of words with another, you use a syntax of `s/{old text}/{new text}`.
