### ISSUE TITLE
Update /jobfair for 2015 Fair

### ISSUE THREAD

**Issue by eunicekokor** [adicu/adi-website#235]

**Comment by eunicekokor** [comment]
@anshulkgupta 
Right now I'm going to update date, time, location, remove links to last year's things and then list the 2015 companies as "coming soon".

**Comment by anshulkgupta** [comment]
alright @eunicekokor how can I help/ how does the deployment process for this work?

**Comment by eunicekokor** [comment]
1) I can make the changes
2) put what you want the changes to be and I can get them up by tonight

**Comment by anshulkgupta** [comment]
it'll be great if you can get the initial skeleton up? I'll take care of putting the companies up and updating the blurbs/sign up form etc. later in the process if that's cool

**Comment by eunicekokor** [comment]
after you fork then clone the repo there is a 'companies.json' with all
the 14 companies that you can change.
also the 'jobfair.html' page is where you can update links.

**Comment by anshulkgupta** [comment]
awesome thanks! we're yet to get the blurbs etc in place so lets go ahead and leave the current companies up as "Last year's attendees are below. We'll be confirming this year's companies shortly." or something?

**Comment by eunicekokor** [comment]
okay! one last question. Any interest in preserving each year's page? like /jobfair-2014 or /jobfair-2015

**Comment by danrschlosser** [comment]
Maybe do /jobfair as the latest, and jobfair-2014?
