### ISSUE TITLE
Change Homepage Header Picture

### ISSUE THREAD

**Issue by eunicekokor** [adicu/adi-website#236]
- [Contender #1] (https://scontent.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/s720x720/1511117_801629349872917_8238610334436555485_n.jpg?oh=a16c2d64e2b1fc8aac602ef3fc7f59d5&oe=5675CCDB)

**Comment by danrschlosser** [comment]
Do we have any other good photos?

**Comment by eunicekokor** [comment]
Going through Flickr right now, where are other photos? Best pics are hq

After testing about half dozen of some of the Flickr pics (also having gender visibility, smiling, something related to 'tech' in mind) these visually look the best as header photos

![screen shot 2015-09-12 at 3 35 02 pm](https://cloud.githubusercontent.com/assets/5273390/9833466/d7c4d056-5965-11e5-9e5f-5f4e212c7d8a.png)

or 

![screen shot 2015-09-12 at 3 37 50 pm](https://cloud.githubusercontent.com/assets/5273390/9833467/d7c4fb6c-5965-11e5-8b35-45d80fdb664b.png)

or 

![screen shot 2015-09-12 at 3 45 35 pm](https://cloud.githubusercontent.com/assets/5273390/9833468/d7c6c6b8-5965-11e5-80b7-b54c11d8d1b0.png)

**Comment by danrschlosser** [comment]
I like all of these!  I can't decide between 2 and 3 as my favorites :)

**Comment by eunicekokor** [comment]
I like #2 best!

**Comment by eunicekokor** [comment]
updated it if that's okay!

On Sat, Sep 12, 2015 at 3:52 PM Dan Schlosser <notifications@github.com>
wrote:

> I like all of these! I can't decide between 2 and 3 as my favorites :)
>
> On Sat, Sep 12, 2015 at 3:50 PM eunice <notifications@github.com> wrote:
>
> > Going through Flickr right now, where are other photos? Best pics are hq
> >
> > After testing about half dozen of some of the Flickr pics (also having
> > gender visibility, smiling, something related to 'tech' in mind) these
> > visually look the best as header photos
> >
> > [image: screen shot 2015-09-12 at 3 35 02 pm]
> > <
> https://cloud.githubusercontent.com/assets/5273390/9833466/d7c4d056-5965-11e5-9e5f-5f4e212c7d8a.png
> >
> >
> > or
> >
> > [image: screen shot 2015-09-12 at 3 37 50 pm]
> > <
> https://cloud.githubusercontent.com/assets/5273390/9833467/d7c4fb6c-5965-11e5-8b35-45d80fdb664b.png
> >
> >
> > or
> >
> > [image: screen shot 2015-09-12 at 3 45 35 pm]
> > <
> https://cloud.githubusercontent.com/assets/5273390/9833468/d7c6c6b8-5965-11e5-80b7-b54c11d8d1b0.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/adicu/adi-website/issues/236#issuecomment-139814229
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adicu/adi-website/issues/236#issuecomment-139814861>.
>
-- 
Eunice Kokor

**Comment by danrschlosser** [comment]
Yup!
