### ISSUE TITLE
deployfail

### ISSUE THREAD

**Issue by eunicekokor** [adicu/adi-website#244]
I was deploying and everything is still live but I got an error and the site isn't updated. :-1: 

![screenshot 2015-09-22 20 32 01](https://cloud.githubusercontent.com/assets/5273390/10035588/dffe9174-6169-11e5-93c1-c9ebe3f872a8.png)

**Comment by danrschlosser** [comment]
I broke errythang sorry

ssl is hard

**Comment by danrschlosser** [comment]
this is fixed, dan did #sslthings

**Comment by natebrennand** [comment]
![](http://www.yiyinglu.com/wp-content/uploads/2013/11/lifting-a-dreamer-2009.jpg)
