### ISSUE TITLE
Create a Style Guide

### ISSUE THREAD

**Issue by eunicekokor** [adicu/adi-website#253]
For documentation purposes & as project groups expand to have their own pages with updates to those pages, it may be useful to do this. [Code for America](https://style.codeforamerica.org/) had a super useful one that I loved using. This would be building off of [Brand Guidelines](https://github.com/adicu/secrets/wiki/Brand-Guidelines). 

also due to organization sometimes I find it hard to distinguish which styles are defined in [`base`](https://github.com/adicu/adi-website/blob/master/app/static/scss/client/base.scss) versus [`client`](https://github.com/adicu/adi-website/blob/master/app/static/scss/client/client.scss) and if any of the [`component`](https://github.com/adicu/adi-website/tree/master/app/static/scss/client/components) sass objects (i.e. single, triple) make sense to be their own sass objects or in base or client. I'm down for adding this to the READMEs, too!

Thoughts? @danrschlosser @RaymondXu

**Comment by danrschlosser** [comment]
Totally love this!  Yeah We could definitely use a reorg of this stuff.
