### ISSUE TITLE
Fix or remove broken rails resource link

### ISSUE THREAD

**Issue by emilypries** [adicu/adi-website#258]
The "Official Ruby on Rails Tutorial" link is broken on /resources

http://ruby.railstutorial.org/ruby-on-rails-tutorial-book

**Comment by danrschlosser** [comment]
The correct link is https://www.railstutorial.org/book

**Comment by eunicekokor** [comment]
kk I'm also trying to add this presentation: https://docs.google.com/presentation/d/1r2-hqDJjt_OTEdsvdQnCbZg6RVfQp5jnlzLM7hofHbg/

**Comment by danrschlosser** [comment]
Could we host it somewhere where you don't need to sign in to view it?
Maybe export to pdf or something?  or permissions?

**Comment by eunicekokor** [comment]
closed via #265. I have to text Helson to update permissions before I add that link.
