### ISSUE TITLE
Find the next cookies and code button brings you to a 404 

### ISSUE THREAD

**Issue by freeslugs** [adicu/adi-website#262]
main page, green div, "Find the next Cookies and Code" button, brings you to https://adicu.com/events/cookies-and-code which doesn't exist.

**Comment by eunicekokor** [comment]
Thanks for the find! Will fix!
On Wed, Dec 2, 2015 at 7:00 PM Gilad Penn <notifications@github.com> wrote:

> main page, green div, "Find the next Cookies and Code" button, brings you
> to https://adicu.com/events/cookies-and-code which doesn't exist.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adicu/adi-website/issues/262>.
>
-- 
Eunice Kokor

**Comment by eunicekokor** [comment]
closed with #265
