### ISSUE TITLE
Wrong link to form on contact page

### ISSUE THREAD

**Issue by evantarrh** [adicu/adi-website#269]
Should link to this one: https://docs.google.com/a/adicu.com/forms/d/1rP0epIrBmFwIxrzSN0eqq_-pznytpdBa_qc5k1aUx4c/viewform

The current form is outdated/no longer in use

**Comment by evantarrh** [comment]
Happy to take care of this but have never worked on the site before!

**Comment by eunicekokor** [comment]
:+1:
