### ISSUE TITLE
Weekly Email summaries

### ISSUE THREAD

**Issue by danrschlosser** [adicu/adi-website#81]
<a href="https://github.com/danrschlosser"><img src="https://avatars.githubusercontent.com/u/2433509?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [danrschlosser](https://github.com/danrschlosser)**
_Thursday Oct 09, 2014 at 03:38 GMT_
_Originally opened as https://github.com/danrschlosser/eventum/issues/81_

----

Every week, send an email summarizing the events.

Add a "settings" page to allow admins to customize who the email gets sent to

The email could look like:

------
## Published Events

- event1 <--- link to event
- event2 

## Unpublished Events

- event1 
- event2

## Events next week

- event1 
- event2

**Comment by danrschlosser** [comment]
I think @jettca's mailchimp script will make this useless, right?

**Comment by jettca** [comment]
it'll make it useless for adi but perhaps not for eventum in general, since my script has a bunch of features specific to our use-cases.

**Comment by danrschlosser** [comment]
Yeah it was going to be for adi-website, not eventum anyway, so ima close this
